/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7662566c-a685-4025-bc6a-e3268dcf1039",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MfonfBLIp",
    "aws_user_pools_web_client_id": "7mfnl2gr7ai268upofoav0l116",
    "oauth": {}
};


export default awsmobile;
